#include<stdio.h>
#include<conio.h>
#include<math.h>
main()
{
int f[10], g[10][10],msg[10],op[10][10];
int i,j,k,n,r,c,p;
clrscr();

for (i=0;i<=9;i++)
f[i]=0;

printf("enter no. of input bits applied to conv enc");
scanf("%d",&k);
printf("enter no. of output bits generated by conv enc");
scanf("%d",&n);
printf("enter no. of flip flops conv enc");
scanf("%d",&r);
printf("enter generating functions of conv enc");
for(i=1;i<=n;i++)
{
	printf("\n for adder %d",i);

	for(j=0;j<=r;j++)
	      {
		scanf("%d",&g[i][j]);
	      }

}
printf("enter no. of msg bits");
scanf("%d",&c);

	for(j=1;j<=c+r;j++)

	      {
	       if(j<=c)
	       {
		printf("\n enter msg bit %d",j);
		scanf("%d",&msg[j]);
		}
		else
		msg[j]=0;
		  }
	for(i=1;i<=r+c;i++)   //for op bits msg
		{
		  for (p=1;p<=n;p++)
		  {
			op[p][i]=0;
			for(j=0;j<=r;j++)  //for op bits no. of flip flops
			{
			 f[0]=msg[i];
			 if(g[p][j]==1)
				 {
				op[p][i]=op[p][i]^f[j];
				 }
			 }



		  }
		  for(j=r;j>=1;j--)  //for op bits no. of flip flops
			{
				f[j]=f[j-1];
			}
		}

	   for(i=1;i<=n;i++)
	   {
		for(j=1;j<=r+c;j++)
		{
			printf(" %d", op[i][j]);
		}
		printf("\n");
	   }
	   getch();
 }

